### ISSUE TITLE
Unable to find element containing a non-breaking space

### ISSUE THREAD

**Issue by johnbillion** [minkphp/Mink#647]
Forgive me for the lack of detail, I'm unsure exactly where in the stack this problem lies.

Given a page with a link which contains a non-breaking space, thus:

```
<a href="#">Hello&nbsp;world</a>
```

It's not possible to find or click this link.

```
$this->clickLink( 'Hello world' );
$this->clickLink( 'Hello&nbsp;world' );
```

Both of the above fail with:

```
Link with id|title|alt|text "Hello world" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

I'm using Behat 3.0, Mink and mink-extension from the master branch, and the Goutte driver.

**Comment by aik099** [comment]
Does it work with different driver?

**Comment by stof** [comment]
Can you try when searching for the string with a non-breaking space in it ?

```php
$this->clickLink("Hello\xc2\xa0world");
```

``&nbsp;`` is *not* a non breaking space in PHP. It is only representing such char after parsing the HTML.

**Comment by johnbillion** [comment]
@stof Thank you, using `"Hello\xc2\xa0world"` works.

**Comment by aik099** [comment]
@johnbillion , if issue was solved don't forget to press "Close" button.

**Comment by uuf6429** [comment]
Here are my two cents on this matter:
- In principle, it should work in Behat+Mink because it's what the user sees & does
- In particular, it took me a while to realise that the failure was due to `&nbsp;`
- From what I tried, it won't work when one pastes `"Hello\xc2\xa0world"` in the feature file (makes sense since escaped characters are meaningless in the feature file)
- However, pasting those actual bytes in the feature file still didn't make it work (IDK why)

So what solutions do we end up with?
- patching mink (I have a feeling this won't be done)
- creating specific steps in a custom context (eg; `And I follow the Hello World link`):
  ```php
    public function followHelloWorldLink()
    {
        $this->clickLink("Hello\xc2\xa0world");
    }
  ```
- having your own MinkContext with a step that decodes the characters from the feature file:
   ```php
    public function clickLink($link)
    {
        parent::clickLink(htmlspecialchars_decode($link));
    }
   ```
   I'm not sure if this is possible, I have a feeling behat would complain that the step is defined twice.

In my cases, I opted for the 2nd option since I already have an application-specific custom context - but it still feels like it is the cleanest _hack_ available.
