### ISSUE TITLE
shared sessionStrategy: UnknownError when getSession() called in second test method

### ISSUE THREAD

**Issue by Jodes81** [minkphp/Mink#661]
I have come across the error when modifying the "GeneralTest" class given in the examples.

To reproduce: 

1. I add this to the $browser array: 'sessionStrategy' => 'shared'
2. I copy the method testUsingSession() and paste as testUsingSession2()

For now, the only workaround I have is to omit the shared session declaration and have a new browser window load for each test method - *very* slow.

**Comment by aik099** [comment]
The shared session concept comes from `minkphp/phpunit-mink` repo. You should be reporting there instead of this `minkphp/Mink` repo.

**Comment by aik099** [comment]
Can you please describe what you want to achieve instead?

**Comment by Jodes81** [comment]
It's my first project with Mink and Behat and am still getting a feel for it all. Thanks for pointing me to phpunit-mink, just what I've been looking for.

I just wanted to speed up tests, sharing sessions seems like a fundamental I need to get working!

Thanks for your help

**Comment by aik099** [comment]
When you create task in correct repo post link to it here so it can be tracked properly.

Talking about terminology:

* Behat + Mink = use gherkin language to write scenarios + run them using Behat feature context classes
* PHPUnit-Mink + Mink = write PHPUnit tests directly using Mink language

PHPUnit-Mink + Behat + Mink isn't really a possibility, because you can use either 2 together.

**Comment by Jodes81** [comment]
I have raised the issue for phpunit-mink here:

https://github.com/minkphp/phpunit-mink/issues/53
