### ISSUE TITLE
Provide a way to interact with only visible elements

### ISSUE THREAD

**Issue by tuxayo** [minkphp/Mink#712]
From what I understand, `findAll` doesn't filter out invisible elements.

It would be useful to have a way to only use visible elements. Because not doing so can lead to tests that don't represent the reality because of elements being hidden by others, not here because JS hasn't finished, etc.

Some links about the issues when manipulating invisible elements and ideas how we could choose to avoid that:
https://spin.atomicobject.com/2013/02/13/capybara-hidden-dom-elements/
https://stackoverflow.com/questions/8801845/how-to-make-capybara-check-for-visibility-after-some-js-has-run/8818598#8818598

**Comment by aik099** [comment]
Ability to determine if element is visible to the user exist only in some of Mink drivers, including Selenium2. Other drivers, either don't have it at all (e.g. BrowserKit) or emulate it (e.g. Zombie). There is also the `NodeElement::isVisible` method that uses driver ability to detect if element is visible.

Unfortunately there is no way to make all `find*` calls to account for visible elements only, because it will make all work 2x slower due additional visibility checks.

If we're talking about single case only (e.g. you only need it somewhere once, but not all the time), then you can use code like this:

```php

$page = $session->getPage();
$element = $page->waitFor(5, function($page) {
    $found = $page->find(....);

    if ( $found !== null && $found->isVisible() ) {   
        return $found;
    }

    return null;
});
```

The above code will not only wait 5 seconds max for element to appear (naturally `find*` method don't do that), but also will only yield element back to calling code, when it becomes visible.

**Comment by tuxayo** [comment]
> Unfortunately there is no way to make all find* calls to account for visible elements only, because it will make all work 2x slower due additional visibility checks.

I see, I meant having a choice, not replacing the current behavior.

Thanks for the example, would adding such a function to Mink be useful? (working only with drivers that support it of course) or making find() take an optional param to use the waiting version.

**Comment by aik099** [comment]
Adding `NodeElement::findVisible(...)` and `NodeElement::findAllVisible` doesn't seem like a big problem. However all methods that use `find` and `findAll` indirectly (e.g. all `WebAssert` class, used from Behat) won't be able to use them.

**Comment by tuxayo** [comment]
If that's too much work before getting significant value then no problem. Thanks for your answers and great work! :)
