### ISSUE TITLE
Unclear method names

### ISSUE THREAD

**Issue by spolischook** [minkphp/Mink#719]
I have confusion about names of methods in a DriverInterface->find and ElementInterface->find.
You know what I'm about?
It would be more clear to have methods as Doctrine have - findOne and findAll in both Driver and Element interfaces.
I can add this changes to ```2-architecture-changes``` if you approve this.

**Comment by stof** [comment]
No, the driver should not have several ways to find elements.

Btw, you should never need to use the driver directly. It is the internal layer of Mink. Unless you work on Mink itself, you should only be using the Session and the Element API (and the WebAssert which is at a higher level too)

**Comment by spolischook** [comment]
Ok, I what to follow Mink architecture but it's not clear methods names anyway. 
I close this issue, maybe I will back to it later.

**Comment by aik099** [comment]
I guess @spolischook was also talking about `ElementInterface`, which is used by `NodeElement` and `DocumentElement`, which are pretty high level. Renaming `NodeElement::find` into `NodeElement::findOne` alone won't be of much help since related classes (e.g. `WebAssert`) would still use `find` instead of `findOne` in their names.

**Comment by spolischook** [comment]
Yes I mean ```ElementInterface```.
And also, I don't like that Driver (or ElementFinder) creates a set of NodeElements instead of return One or Many of that. I think that it's more simple to move [this logic](https://github.com/spolischook/Mink/blob/d594cd90f18e8040972d8fcbc6e747ae69f17817/src/Element/Element.php#L104-L104):

```php
return count($items) ? $items[0] : null;
```
to the Driver/ElementFinder layer.

**Comment by aik099** [comment]
> And also, I don't like that Driver (or ElementFinder) creates a set of NodeElements instead of return One or Many of that.

What? The driver finds the elements and returns `NodeElement` array in any case with found elements. What's incorrect in here? The specified above code (in the link) is from Element, not driver. Element can do whatever it needs with received array. The driver doesn't care about one/many and don't have any business logic, while Element does. That's why code is placed where it is.

**Comment by spolischook** [comment]
Ok, so why it doesn't return array of xpaths, and then Element can get first string and wrap it to NodeElement?

**Comment by stof** [comment]
@spolischook this is what drivers will do in Mink 2.0 (see the PR containing 2.0 changes so far)

**Comment by spolischook** [comment]
Oh, I see that method now named as ```findAll```. It's nice.
But maybe we can add findOne to ```ElementFinder``` and use it in Elements?

**Comment by stof** [comment]
Well, in the Element API, we have ``find`` for a single element and ``findAll`` for all elements.

ElementFinder is also an internal API btw

**Comment by spolischook** [comment]
> ElementFinder is also an internal API btw

Yes, I understand, this issue is in Mink repository context, it's clear.

> in the Element API, we have ```find``` for a single element and ```findAll```

In my point of view ```findOne``` is more convenient name for the ```find``` method.
However ```find``` method filter ```NodeElements``` that it gets from ```findAll``` method, instead of filtering strings and wrap the first one to the ```NodeElement```

**Comment by stof** [comment]
@spolischook renaming ``find`` to ``findOne`` without also renaming ``findButton`` and all other ``find`` shortcut would probably also look weird.
And is renaming ``find`` to ``findOne`` worth the BC break ? AFAIK, you are the first one in years asking for such a renaming.

> However find method filter NodeElements that it gets from findAll method, instead of filtering strings and wrap the first one to the NodeElement

This is because drivers themselves are responsible to build NodeElement instance in Mink 1.x (and it cannot change for BC reasons), and so the element never receives the XPath string.
And for now, I kept calling findAll in 2.x as well, because it makes the code much simpler (no need to duplicate all the logic about finding elements and building a NodeElement. And this is not an issue for users, as they don't care about how we implement it internally. Regarding contributors, duplicating the finding logic just to avoid instantiating extra NodeElement instance does not look a sane approach to me.

**Comment by spolischook** [comment]
> renaming ```find``` to ```findOne``` without also renaming ```findButton``` and all other ```find``` shortcut would probably also look weird.

No, because for buttons it might be ```findButtons```.

> duplicating the finding logic just to avoid instantiating extra NodeElement instance does not look a sane approach to me.

There is no reasons to duplicate logic.
The main reason that I what to get xpath(s) instead of ```NodeElement``` because I don't really like ```NodeElement``` - it takes too much responsibility. It has behavior from all elements at all. All I need is xpath to element, and let elements layer decide what element to create.

**Comment by spolischook** [comment]
E.g. if I find text input I don't want to have method to ```check``` or ```uncheck``` it - it does not make sense

**Comment by aik099** [comment]
You don't like it in general or you have any specific reasons why `NodeElement` having many methods is bad for you?

The `NodeElement` is like `WebElement` in Java. It has all methods (for buttons, links, divs, etc.) on it and I saw nobody complain about that fact.

**Comment by aik099** [comment]
> E.g. if I find text input I don't want to have method to check or uncheck it - it does not make sense

If you want to have more on-topic API, then please use https://github.com/qa-tools/qa-tools abstraction layer over Mink. It uses NodeElement internally, but you deal with specific classes, e.g.

* Button
* Link
* ...

that have only dedicated public methods. It also provides ability to use PageObject pattern during test writing.

**Comment by spolischook** [comment]
@aik099 Thanks for your contribution - I'm already planned time to investigate your repository.

**Comment by aik099** [comment]
So I guess issue is resolved then, @spolischook ?

**Comment by spolischook** [comment]
ok
