### ISSUE TITLE
Inject ElementFactoryInterface into DriverInterface

### ISSUE THREAD

**Issue by spolischook** [minkphp/Mink#737]
I suggest to have setter injection as well as setSession.

```php
    /**
     * Sets ElementFactory
     *
     * @param ElementFactoryInterface $elementFactory
     */
    public function setFactory(ElementFactoryInterface $elementFactory);
```
The issue in Single Responsibility Principe

**Comment by stof** [comment]
-1 for that. We actually plan to remove the session injection entirely in Mink 2.x and having the driver itself being unaware of NodeElement at all. So I don't want to add a new method in drivers to inject this separate object, which will be unnecessary at the same time than the session.

btw, you should never deal with the driver layer yourselves unless you want to implement your own driver (and in this case, you should not care about the session itself, as recent versions of Mink deal with it in the parent class being provided, making your own driver ready for Mink 2). Code using Mink (rather than implementing drivers) would only need to access the driver when they need to access the underlying implementation (i.e. using `getDriver()->getWebdriverSession()` to use Selenium directly for a case not covered by the abstraction for instance). Any usage of the Mink API should happen in higher level API. So most users won't care about what happens in the driver.

**Comment by stof** [comment]
btw, even when instantiating the driver, you should not be calling `setSession` yourselves anyway.
