### ISSUE TITLE
Mink & Selenium - SetRequestHeader not accepted by Selenium

### ISSUE THREAD

**Issue by cedricherve** [minkphp/Mink#769]
I am using Mink with Behat to interface with a selenium jar which is runing (java -jar selenium.standalone2.45.jar)

1st scenario : I want to access an application which ask for a custom header in request to pass authentication, 

To do so, I execute a mink method

`$session->setRequestHeader('my_custom_header','<USER_ID>');`

The problem is that Selenium disallow this customization

Message : `Request headers manipulation is not supported by Behat\Mink\Driver\Selenium2Driver (Behat\Mink\Exception\UnsupportedDriverActionException)`

I don't if it should be Mink issue or Selenium limitation, anyway If you have a workaround to do it :)

**Comment by aik099** [comment]
The Selenium Server is controlling real Web Browser and emulating user actions in it. User can't set headers while visiting web page and that's why Selenium2 Driver doesn't allow it either.

If you'll find it's actually possible via some WebDriver API, then please send a PR to the https://github.com/minkphp/MinkSelenium2Driver .

**Comment by stof** [comment]
there is no such API in webdriver. This is a Selenium limitation.
